const userActionTypes = {
    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
    LOGOUT_USER: 'LOGOUT_USER'
}

export default userActionTypes;