const userActionTypes = {
    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
    LOGOUT_USER: 'LOGOUT_USER',
    SIGNIN_USER_START: 'SIGNIN_USER_START',
    SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
    SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE'
}

export default userActionTypes;