const userActionTypes = {
    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
    LOGOUT_USER: 'LOGOUT_USER',
    SIGNIN_USER_START: 'SIGNIN_USER_START',
    SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
    SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',
    UPDATE_CURRENTUSER_SUCCESS: 'UPDATE_CURRENTUSER_SUCCESS',
    UPDATE_CURRENTUSER_FAILURE: 'UPDATE_CURRENTUSER_FAILURE',
    CLEAR_USERFORM_ERROR: 'CLEAR_USERFORM_ERROR'
}

export default userActionTypes;