const postActionTypes = {
    CREATE_POST_START: 'CREATE_POST_START',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
    GET_USERPOSTS_START: 'GET_USERPOSTS_START',
    GET_USERPOSTS_SUCCESS: 'GET_USERPOSTS_SUCCESS',
    GET_USERPOSTS_FAILURE: 'GET_USERPOSTS_FAILURE',
    UPDATE_POST_START: 'UPDATE_POST_START',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE'
}

export default postActionTypes;